# kubernetes/backstage-secrets.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "postgres.backstage.svc.cluster.local"
  CATALOG_LOCATION: "https://github.com/guymenahem/backstage/blob/backstage-argo-workshop/backstage-argocd-workshop/deploy/sample-application/app-component.yaml"
  BASE_URL: "localhost"
